### ISSUE TITLE
HW 05.10.2017 Testing

### ISSUE THREAD

**Issue by alexvishneuski** [IstiN/android-training-2017#46]
This is link on my calculator. 

https://github.com/alexvishneuski/SimpleAndroidCalculator.git

But I'm getting following error when I run my RobolectricTests:

No such manifest file: build\intermediates\bundles\debug\AndroidManifest.xml

"C:\Program Files\Android\Android Studio\jre\bin\java" -Didea.launcher.port=7539 "-Didea.launcher.bin.path=C:\Program Files\Android\Android Studio\bin" -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Android\Android Studio\lib\idea_rt.jar;C:\Program Files\Android\Android Studio\plugins\junit\lib\junit-rt.jar;C:\Java\AndroidSDK\platforms\android-26\data\res;D:\android\Epam\SimpleAndroidCalculator\app\build\intermediates\classes\test\debug;D:\android\Epam\SimpleAndroidCalculator\app\build\intermediates\classes\debug;C:\Users\admin\.gradle\caches\modules-2\files-2.1\backport-util-concurrent\backport-util-concurrent\3.1\682f7ac17fed79e92f8e87d8455192b63376347b\backport-util-concurrent-3.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-profile\2.2.1\3950071587027e5086e9c395574a60650c432738\maven-profile-2.2.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\nekohtml\xercesMinimal\1.9.6.2\d1c5e063683a0e6f77cd5f051a9d4af48346fa6\xercesMinimal-1.9.6.2.jar;C:\Users\admin\.android\build-cache\95d4aca5d6a7ef835ef93e4523e52ab8382356f0\output\jars\classes.jar;C:\Users\admin\.android\build-cache\95d4aca5d6a7ef835ef93e4523e52ab8382356f0\output\res;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-settings\2.2.1\2236ffe71fa5f78ce42b0f5fc22c54ed45f14294\maven-settings-2.2.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-library\1.3\4785a3c21320980282f9f33d0d1264a69040538f\hamcrest-library-1.3.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-commons\5.0.1\7b7147a390a93a14d2edfdcf3f7b0e87a0939c3e\asm-commons-5.0.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.google.android.apps.common.testing.accessibility.framework\accessibility-test-framework\2.1\c2d6267c3ad0435ddf9e27a94a0e0af4ca3fdfbb\accessibility-test-framework-2.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-http-lightweight\1.0-beta-6\b3815078570c3b1f0667e123d59717c6b726c6c2\wagon-http-lightweight-1.0-beta-6.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\nekohtml\nekohtml\1.9.6.2\2d960be7b62ae6622dbbbe49ab4ffdc609f85c80\nekohtml-1.9.6.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm\5.0.1\2fd56467a018aafe6ec6a73ccba520be4a7e1565\asm-5.0.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-repository-metadata\2.2.1\98f0c07fcf1eeb213bef8d9316a9935184084b06\maven-repository-metadata-2.2.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.google.guava\guava\20.0\89507701249388e1ed5ddcf8c41f4ce1be7831ef\guava-20.0.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.robolectric\junit\3.4.2\7996c0581ab5af01bcdaf60399845bc17c7109ca\junit-3.4.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.mockito\mockito-core\1.10.19\e8546f5bef4e061d8dd73895b4e8f40e3fe6effe\mockito-core-1.10.19.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.robolectric\framework\3.4.2\ce238cfb5437aca37e9bfd83fca8ee8225268c64\framework-3.4.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-model\2.2.1\c0a1c17436ec3ff5a56207c031d82277b4250a29\maven-model-2.2.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\xmlpull\xmlpull\1.1.3.1\2b8e230d2ab644e4ecaa94db7cdedbc40c805dfa\xmlpull-1.1.3.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.robolectric\annotations\3.4.2\5b3b051b961e2bc5b6f3482ddd4cef068265ab80\annotations-3.4.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.ibm.icu\icu4j\53.1\786d9055d4ca8c1aab4a7d4ac8283f973fd7e41f\icu4j-53.1.jar;C:\Users\admin\.android\build-cache\8a1dc300bfd6923de8cb923fdb32a7f8b215bf62\output\jars\classes.jar;C:\Users\admin\.android\build-cache\8a1dc300bfd6923de8cb923fdb32a7f8b215bf62\output\res;C:\Users\admin\.android\build-cache\b447d983e23f41a35ef19fbf8ba3633a7ecbaac3\output\res;C:\Users\admin\.android\build-cache\b447d983e23f41a35ef19fbf8ba3633a7ecbaac3\output\jars\classes.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-tree\5.0.1\1b1e6e9d869acd704056d0a4223071a511c619e6\asm-tree-5.0.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.robolectric\resources\3.4.2\c2b6304d1f88830ef691e31da2d5ae7e85b4acdd\resources-3.4.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.almworks.sqlite4java\sqlite4java\0.282\745a7e2f35fdbe6336922e0d492c979dbbfa74fb\sqlite4java-0.282.jar;C:\Users\admin\.android\build-cache\3728bd61fbdf9deab84b3b32c1247308a6a7f15f\output\jars\classes.jar;C:\Users\admin\.android\build-cache\3728bd61fbdf9deab84b3b32c1247308a6a7f15f\output\res;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-project\2.2.1\8239e98c16f641d55a4ad0e0bab0aee3aff8933f\maven-project-2.2.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.robolectric\sandbox\3.4.2\1f3a9f6d8b4942749524e64661333e8478a65473\sandbox-3.4.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-container-default\1.0-alpha-9-stable-1\94aea3010e250a334d9dab7f591114cd6c767458\plexus-container-default-1.0-alpha-9-stable-1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.robolectric\shadowapi\3.4.2\c49993ea80f9df979d47f366248e6cfbcc732569\shadowapi-3.4.2.jar;C:\Java\AndroidSDK\extras\android\m2repository\com\android\support\support-annotations\26.0.0-alpha1\support-annotations-26.0.0-alpha1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\classworlds\classworlds\1.1-alpha-2\5adf2e681c57d7f48038b602f3ca2254ee82d47\classworlds-1.1-alpha-2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-interpolation\1.11\ad9dddff6043194904ad1d2c00ff1d003c3915f7\plexus-interpolation-1.11.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-artifact-manager\2.2.1\ec355b913c34d37080810f98e3f51abecbe1572b\maven-artifact-manager-2.2.1.jar;C:\Users\admin\.android\build-cache\7c2eae1ef5c5c09f9ed587954435a3d83550f133\output\jars\classes.jar;C:\Users\admin\.android\build-cache\7c2eae1ef5c5c09f9ed587954435a3d83550f133\output\res;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-ant-tasks\2.1.3\b09be554228d66d208e5fef5266844aacf443abc\maven-ant-tasks-2.1.3.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.ant\ant\1.8.0\7b456ca6b93900f96e58cc8371f03d90a9c1c8d1\ant-1.8.0.jar;C:\Users\admin\.android\build-cache\68a68137f540632f21111c8382d805f612e02194\output\res;C:\Users\admin\.android\build-cache\68a68137f540632f21111c8382d805f612e02194\output\jars\classes.jar;C:\Users\admin\.android\build-cache\93d0eaf7afb88515271a43f53259e2ac2e3c4e87\output\jars\classes.jar;C:\Users\admin\.android\build-cache\93d0eaf7afb88515271a43f53259e2ac2e3c4e87\output\res;C:\Users\admin\.android\build-cache\ae451adda1df3a872f87948f700d5313c414e516\output\res;C:\Users\admin\.android\build-cache\ae451adda1df3a872f87948f700d5313c414e516\output\jars\classes.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.ant\ant-launcher\1.8.0\8b53ba16fa62fb1034da8f1de200ddc407c8381\ant-launcher-1.8.0.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\xpp3\xpp3_min\1.1.4c\19d4e90b43059058f6e056f794f0ea4030d60b86\xpp3_min-1.1.4c.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-error-diagnostics\2.2.1\e81bb342d7d172f23d108dc8fa979a1facdcde8e\maven-error-diagnostics-2.2.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-file\1.0-beta-6\6c53633505460caf49d2660de1e24744d915afb9\wagon-file-1.0-beta-6.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.thoughtworks.xstream\xstream\1.4.8\520d90f30f36a0d6ba2dc929d980831631ad6a92\xstream-1.4.8.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-provider-api\1.0-beta-6\3f952e0282ae77ae59851d96bb18015e520b6208\wagon-provider-api-1.0-beta-6.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk16\1.46\ce091790943599535cbb4de8ede84535b0c1260c\bcprov-jdk16-1.46.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.robolectric\utils\3.4.2\7e836faf87847237ae62809273373cda709be6ce\utils-3.4.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-http-shared\1.0-beta-6\ccd70d7e0d8c085e648a83f072da06ca9a53be94\wagon-http-shared-1.0-beta-6.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.objenesis\objenesis\2.1\87c0ea803b69252868d09308b4618f766f135a96\objenesis-2.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-artifact\2.2.1\23600f790d4dab2cb965419eaa982e3e84c428f8\maven-artifact-2.2.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.robolectric\robolectric\3.4.2\a51a89862fc59fed560984732bfada9db263531e\robolectric-3.4.2.jar;C:\Java\AndroidSDK\extras\m2repository\com\android\support\constraint\constraint-layout-solver\1.0.2\constraint-layout-solver-1.0.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-utils\1.5.15\c689598ce1eb94c304817877ed15911099972526\plexus-utils-1.5.15.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-plugin-registry\2.2.1\72a24b7775649af78f3986b5aa7eb354b9674cfd\maven-plugin-registry-2.2.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protobuf-java\2.6.1\d9521f2aecb909835746b7a5facf612af5e890e8\protobuf-java-2.6.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-core\1.3\42a25dc3219429f0e5d060061f71acb49bf010a0\hamcrest-core-1.3.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\junit\junit\4.12\2973d150c0dc1fefe998f834810d68f278ea58ec\junit-4.12.jar;C:\Users\admin\.android\build-cache\bf2d1df37cc86026ee38abc0ecd95e9563697aa0\output\res;C:\Users\admin\.android\build-cache\bf2d1df37cc86026ee38abc0ecd95e9563697aa0\output\jars\classes.jar;C:\Users\admin\.android\build-cache\d9ebb0c1e49685de6910638962e67e66e8f3068f\output\res;C:\Users\admin\.android\build-cache\d9ebb0c1e49685de6910638962e67e66e8f3068f\output\jars\classes.jar;D:\android\Epam\SimpleAndroidCalculator\app\build\intermediates\sourceFolderJavaResources\test\debug;D:\android\Epam\SimpleAndroidCalculator\app\build\intermediates\sourceFolderJavaResources\debug;D:\android\Epam\SimpleAndroidCalculator\build\generated\mockable-android-26.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 com.github.alexvishneuski.simpleandroidcalculator.RobolectricTest
No such manifest file: build\intermediates\bundles\debug\AndroidManifest.xml

android.content.res.Resources$NotFoundException: Resource ID #0x7f020052

	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:195)
	at android.content.res.Resources.getValue(Resources.java:1315)
	at android.support.v7.widget.AppCompatDrawableManager.createDrawableIfNeeded(AppCompatDrawableManager.java:235)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:198)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:189)
	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:710)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:194)
	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
	at android.support.v7.app.AppCompatDelegateImplBase.__constructor__(AppCompatDelegateImplBase.java:129)
	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java)
	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java)
	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java)
	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java)
	at android.support.v7.app.AppCompatDelegateImplV23.<init>(AppCompatDelegateImplV23.java)
	at android.support.v7.app.AppCompatDelegateImplN.<init>(AppCompatDelegateImplN.java)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:200)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:184)
	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:518)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:70)
	at com.github.alexvishneuski.simpleandroidcalculator.CalculatorActivity.onCreate(CalculatorActivity.java:35)
	at android.app.Activity.performCreate(Activity.java:6975)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:232)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:73)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:366)
	at org.robolectric.shadows.CoreShadowsAdapter$1.runPaused(CoreShadowsAdapter.java:27)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:70)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:80)
	at com.github.alexvishneuski.simpleandroidcalculator.RobolectricTest.testOperation(RobolectricTest.java:48)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:497)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:228)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

	at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:356)
	at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:325)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:286)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
	at com.github.alexvishneuski.simpleandroidcalculator.CalculatorActivity.onCreate(CalculatorActivity.java:37)
	at android.app.Activity.performCreate(Activity.java:6975)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:232)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:73)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:366)
	at org.robolectric.shadows.CoreShadowsAdapter$1.runPaused(CoreShadowsAdapter.java:27)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:70)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:80)
	at com.github.alexvishneuski.simpleandroidcalculator.RobolectricTest.testActivityRun(RobolectricTest.java:36)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:497)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:228)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code -1

I ask very much to help mу.

**Comment by alexvishneuski** [comment]
![red color](https://user-images.githubusercontent.com/31639852/31423149-85c91af8-ae5b-11e7-9e93-cb202769832a.jpg)

and in addition to describing the problem I attach the screenshot from AndroidStudio where some files are marked in red

**Comment by pavelkv96** [comment]
If this
![image](https://user-images.githubusercontent.com/29233766/31427391-bfb39888-ae6f-11e7-800d-0899c2e002b8.png)
then
![image](https://user-images.githubusercontent.com/29233766/31427426-e4df1b96-ae6f-11e7-9e56-dec8c154f2e8.png)
![image](https://user-images.githubusercontent.com/29233766/31427439-ef7fa976-ae6f-11e7-930f-fa69a566d1a2.png)
![image](https://user-images.githubusercontent.com/29233766/31427449-ff954d16-ae6f-11e7-8918-0bbad7832483.png)
Save settings and Run)
![image](https://user-images.githubusercontent.com/29233766/31427495-28adefb4-ae70-11e7-8ed8-e0ffe4cffa2b.png)

**Comment by alexvishneuski** [comment]
Thank you very muth  for you quick help. It seems I've passed tests. I thought that this setting is only for "Linux and Mac Users"

**Comment by YauheniMeshkin** [comment]
in verify

**Comment by YauheniMeshkin** [comment]
` @After
    public void destroy() {
//        activityController.pause().stop().destroy();
    }`
Why did you do comment?

**Comment by alexvishneuski** [comment]
Thank you for the comment, I've fixed it. I can't explain it now. Maybe,  initially there was a comment with some text and when I changed it to the code I forgot to make uncomment
https://github.com/alexvishneuski/SimpleAndroidCalculator/commit/331d082d39e0bc768b1d7cbb6d5837f158e5cfb9

**Comment by YauheniMeshkin** [comment]
verified
